# Makefile
# Build a Go library with the current Go version
# By J. Stuart McMurray
# Created 202501005
# Last Modified 202501005

.include "common.mk"

# Generate a go.mod with the current Go version.
go.mod:
	go mod init go_mod_version 2>go_mod_init.err
