# Makefile
# Er, this is awkward...
# By J. Stuart McMurray
# Created 20250816
# Last Modified 20250816

# Dummy makefile, doesn't actually run the example.  Sorry :(

run:
	@echo "Unfortunately, this doesn't actually do anything." >&2; exit 10
.PHONY: run

clean:
.PHONY: clean
